import numpy as np
key = "YOUR_YOUTUBE_API_KEY"  # replace this key value with Youtube API key
arrholo = np.array([
        "Gawr Gura",
        "Ninomae Ina'nis",
        "Amelia Watson",
        "Takanashi Kiara",
        "Mori Calliope",
        "Inugami Korone",
        "Shirakami Fubuki",
        "Houshou Marine",
        "Uruha Rushia",
        "Kiryu Coco",
        "Murasaki Shion",
        "Tokino Sora",
        "Roboco",
        "Sakura Miko",
        "Hoshimachi Suisei",
        "Yozora Mel",
        "Natsuiro Matsuri",
        "Aki Rosenthal",
        "Akai Haato",
        "Minato Aqua",
        "Nakiri Ayame",
        "Yuzuki Choco",
        "Oozora Subaru",
        "Ookami Mio",
        "Nekomata Okayu",
        "Usada Pekora",
        "Shiranui Flare",
        "Shirogane Noel",
        "Amane Kanata",
        "Tsunomaki Watame",
        "Tokoyami Towa",
        "Himemori Luna",
        "Yukihana Lamy",
        "Momosuzu Nene",
        "Shishiro Botan",
        "Omaru Polka",
        "AZKi",
        "Ayunda Risu",
        "Moona Hoshinova",
        "Airani Iofifteen",
        "Kureiji Ollie",
        "Anya Melfissa",
        "Pavolia Reine",
        "Hanasaki Miyabi",
        "Kanade Izuru",
        "Arurandeisu",
        "Rikka",
        "Astel Leda",
        "Kishido Temma",
        "Yukoku Roberu",
        "Kageyama Shien",
        "Aragami Oga",
        "Nanashi Mumei",
        "Tsukumo Sana",
        "Ceres Fauna",
        "Ouro Kronii",
        "Hakos Baelz",
        "IRyS",
        "Omegaα"

])
arrcolors = np.array([
    '#00769F',
    '#685980',
    '#FDE8CF',
    '#FF8664',
    '#E55A71',
    '#C39088',
    '#E7E5E3',
    '#C36778',
    '#76CFBA',
    '#FF9460',
    '#534159',
    '#16125F',
    '#AC7C24',
    '#F27D83',
    '#7AABE8',
    '#FDEB8B',
    '#72B6C3',
    '#F2DCBA',
    '#F45471',
    '#DA9ED0',
    '#901427',
    '#10346F',
    '#6BCBDA',
    '#292726',
    '#C558FF',
    '#AEC4EF',
    '#B74C25',
    '#68956E',
    '#3485F2',
    '#FFFEDC',
    '#7C6EAC',
    '#FAAFDB',
    '#C6EEF5',
    '#41912D',
    '#888184',
    '#9369A7',
    '#F7057B',
    '#FFB8B9',
    '#AF9EDC',
    '#FFF5F1',
    '#DB1644',
    '#96777F',
    '#164F95',
    '#BA3D39',
    '#545454',
    '#48756D',
    '#E8CABF',
    '#385ECE',
    '#F1D4A5',
    '#C14C2B',
    '#1B1E26',
    '#739427',
    '#BCA999',
    '#E29782',
    '#C6EBBF',
    '#51576F',
    '#F61C12',
    '#2A1929',
    '#C3A7CB'

])
urlist = [
            'UCoSrY_IQQVpmIRZ9Xf-y93g',
            'UCMwGHR0BTZuLsmjY_NT5Pwg',
            'UCyl1z3jo3XHR1riLFKG5UAg',
            'UCHsx4Hqa-1ORjQTh9TYDhww',
            'UCL_qhgtOy0dy1Agp8vkySQg',
            'UChAnqc_AY5_I3Px5dig3X1Q',
            'UCdn5BQ06XqgXoAxIhbqw5Rg',
            'UCCzUftO8KOVkV4wQG1vkUvg',
            'UCl_gCybOJRIgOXw6Qb4qJzQ',
            'UCS9uQI-jC3DE0L4IpXyvr6w',
            'UCXTpFs_3PqI41qX2d9tL2Rw',
            'UCp6993wxpyDPHUpavwDFqgg',
            'UCDqI2jOz0weumE8s7paEk6g',
            'UC-hM6YJuNYVAmUWxeIr9FeA',
            'UC5CwaMl1eIgY8h02uZw7u8A',
            'UCD8HOxPs4Xvsm8H0ZxXGiBw',
            'UCQ0UDLQCjY0rmuxCDE38FGg',
            'UCFTLzh12_nrtzqBPsTCqenA',
            'UC1CfXB_kRs3C-zaeTG3oGyg',
            'UC1opHUrw8rvnsadT-iGp7Cg',
            'UC7fk0CB07ly8oSl0aqKkqFg',
            'UC1suqwovbL1kzsoaZgFZLKg',
            'UCvzGlP9oQwU--Y0r9id_jnA',
            'UCp-5t9SrOQwXMU7iIjQfARg',
            'UCvaTdHTWBGv3MKj3KVqJVCw',
            'UC1DCedRgGHBdm81E1llLhOQ',
            'UCvInZx9h3jC2JzsIzoOebWg',
            'UCdyqAaZDKHXg4Ahi7VENThQ',
            'UCZlDXzGoo7d44bwdNObFacg',
            'UCqm3BQLlJfvkTsX_hvm0UmA',
            'UC1uv2Oq6kNxgATlCiez59hw',
            'UCa9Y57gfeY0Zro_noHRVrnw',
            'UCFKOVgVbGmX65RxO3EtH3iw',
            'UCAWSyEs_Io8MtpY3m-zqILA',
            'UCUKD-uaobj9jiqB-VXt71mA',
            'UCK9V2B22uJYu3N7eR_BT9QA',
            'UC0TXe_LYZ4scaW2XMyi5_kw',
            'UCOyYb1c43VlX9rc_lT6NKQw',
            'UCP0BspO_AMEe3aQqqpo89Dg',
            'UCAoy6rzhSf4ydcYjJw3WoVg',
            'UCYz_5n-uDuChHtLo7My1HnQ',
            'UC727SQYUvx5pDDGQpTICNWg',
            'UChgTyjG-pdNvxxhdsXfHQ5Q',
            'UC6t3-_N8A6ME1JShZHHqOMw',
            'UCZgOv3YDEs-ZnZWDYVwJdmA',
            'UCKeAhJvy8zgXWbh9duVjIaQ',
            'UC9mf_ZVpouoILRY9NUIaK-w',
            'UCNVEsYbiZjH5QLmGeSgTSzg',
            'UCGNI4MENvnsymYjKiZwv9eg',
            'UCANDOlYTJT7N5jlRC3zfzVA',
            'UChSvpZYRPh0FvG4SJGSga3g',
            'UCwL7dgTxKo8Y4RFIKWaf8gA',
            'UC3n5uGu18FoCy23ggWWp8tA',
            'UCsUj0dszADCGbF3gNrQEuSQ',
            'UCO_aKKYxn4tvrqPjcTzZ6EQ',
            'UCmbs8T6MWqUHP1tIQvSgKrg',
            'UCgmPnx-EEeOrZSg5Tiw7ZRQ',
            'UC8rcEBzJSleTkf_-agPM20g',
            'UCKYyiJwNg2nV7hM86U5_wvw'


]